name: Latest Blog Posts

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

concurrency:
  group: readme-update
  cancel-in-progress: true

jobs:
  update-posts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://suraj.io/index.xml"
          max_post_count: 5
